# Generated by Django 4.2.3 on 2023-07-24 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_category_product_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.CharField(max_length=150),
        ),
    ]
